from contextlib import AbstractContextManager
from typing import Protocol

from app.models.device import Device
from app.models.stats_summary import StatsSummary
from app.models.typing_stat import TypingStat
from app.models.user import User


class DeviceStorage(Protocol):
    def find_device(self, device_id: str) -> Device | None: ...
    def save_device(self, device: Device) -> None: ...
    def find_user(self, user_id: str) -> User | None: ...
    def find_user_by_username(self, username_key: str) -> User | None: ...
    def save_user(self, user: User) -> None: ...
    def list_stats(self, device_id: str, limit: int = 30, offset: int = 0) -> list[TypingStat]: ...
    def stats_summary(self, device_id: str) -> StatsSummary: ...
    def has_stat(self, test_id: str) -> bool: ...
    def find_stat(self, device_id: str, stat_id: str) -> TypingStat | None: ...
    def save_stat(self, stat: TypingStat) -> None: ...
    def delete_stats(self, device_id: str) -> None: ...


class DeviceRepository(Protocol):
    def transaction(self, test_storage=None) -> AbstractContextManager[DeviceStorage]: ...
